/**
 * MIT License
 *
 * Copyright (c) 2022 browsco3
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package cs2263_hw03;

import com.google.gson.Gson;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App {//extends Application {
    // Instance Variables
    private String testText = "Hello json";
    private int testInt = 42;

    App() {}

//    @Override
//    public void start(Stage primaryStage) {
//        StackPane root = new StackPane(new Label("Hello World!"));
//
//        Scene scene = new Scene(root, 800, 600);
//
//        primaryStage.setScene(scene);
//        primaryStage.show();
//
//        new Thread(() -> {
//            try {
//                System.out.println("Hello?");
//                Thread.sleep(5000);
//            } catch (InterruptedException e) {
//                throw new RuntimeException("Should not happen!");
//            }
//
//            System.exit(0);
//        }).start();
//    }

    public static void main(String[] args) {
        App testing = new App();
        Gson jason = new Gson();

        String json = jason.toJson(testing);

        System.out.println(json);
    }
}